### ISSUE TITLE
cvx/pow_cvx error

### ISSUE THREAD

**Issue by qivaijar** [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network#1]
I tried to run the code and change the "istrain" parameter to 1 to train or optimize the parameters. However, this  error notification popped out:

Error using cvx/pow_cvx (line 142)
Disciplined convex programming error:
    Illegal operation: {convex} .^ {2}
    (Consider POW_P, POW_POS, or POW_ABS instead.)

**Comment by JSLee121230** [comment]
Could you tell me your version of MATLAB and CVX? I used MATLAB2019B and CVX2.1. Perhaps a problem with the CVX version differences.

**Comment by qivaijar** [comment]
I used MATLAB R2018b and CVX version 2.1.

**Comment by JSLee121230** [comment]
Thank you. I ran a test on matlab2018b and also check the error you mentioned.
I confirmed that it works properly in matlab2019b, and it seems that power operation is not supported.
