### ISSUE TITLE
Error in solveP3

### ISSUE THREAD

**Issue by trandinhhieu1989** [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network#2]
Dear JSLEE,

Thank you very much for sharing your code. However, it raises an error when I rerun your code as follows in line 41 of file solveP3:
Error using cvx/pow_cvx (line 142) Disciplined convex programming error:     Illegal operation: {convex} .^ {2}
 
Best regards,
Hieu Tran

**Comment by JSLee121230** [comment]
Dear Hieu Tran,

What's your matlab version?
I think that the error was caused by incompatibility between the cvx library and Matlab.

Best regards,
Jongseok Lee

**Comment by trandinhhieu1989** [comment]
Dear Jongseok,

I am using Matlab 2019b. If your code still works well from your side,
maybe it is due to incompatibility between the cvx library and Matlab.

Thank you very much.

-- 

Best regards,

HIEU TRAN DINH



University of Luxembourg – JFK Building

Interdisciplinary Centre for Security, Reliability and Trust

29, Avenue J.F. Kennedy
<https://www.google.com/maps/search/29,+Avenue+J.F.+Kennedy?entry=gmail&source=g>

L-1855 Luxembourg

Office: E04-310

Cellphone: +352 661990737

Work phone: +352 46 66 44 4974
