### ISSUE TITLE
some code debug

### ISSUE THREAD

**Issue by PDmeaning** [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network#3]
there always a bug in Q0 = ((qF - q0)*(m-1)/(M-1)) + q0;, it prompt Matrix dimensions must agree,can you give me some suggestion，thank you

**Comment by JSLee121230** [comment]
It seems that division can cause problems. Can you try replacing `/` with `./`?

**Comment by PDmeaning** [comment]
Thank you for your answer, but there are also the same error in&nbsp;
"Error in parameter_setting (line 57)
Q0 = ((qF - q0)*(m-1)./(M-1)) + q0;


Error in Figure1 (line 35)
&nbsp; &nbsp; parameter_setting('Sk',10*(10^6),'epsilon',10^-2);"&nbsp;
that
"Error using&nbsp; +&nbsp;
Matrix dimensions must agree."



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月9日(星期天) 中午12:08
收件人:&nbsp;"JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"<Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network@noreply.github.com&gt;;
抄送:&nbsp;"蒲丹"<1600397887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network] some code debug (#3)





 
It seems that division can cause problems. Can you try replacing / with ./?

**Comment by JSLee121230** [comment]
Please tell me your matlab version, let me debug it.

**Comment by PDmeaning** [comment]
I'm sorry, I just saw your message, my matlab version is MATLAN R2016a. And then I use matlab 2018a that also only obtain partial pictures, so that errrors may cause by version, Is it because that different versions have different grammer? Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 上午6:25
收件人:&nbsp;"JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"<Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network@noreply.github.com&gt;;
抄送:&nbsp;"蒲丹"<1600397887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network] some code debug (#3)





 
Please tell me your matlab version, let me debug it.

**Comment by JSLee121230** [comment]
I also think the difference between the MATLAB version is causing that problem.
So, i close this issue.
Thanks for reporting the problem.

**Comment by PDmeaning** [comment]
Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 上午7:38
收件人:&nbsp;"JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"<Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network@noreply.github.com&gt;;
抄送:&nbsp;"蒲丹"<1600397887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network] some code debug (#3)





 
Closed #3.
