### ISSUE TITLE
There may be some problems here

### ISSUE THREAD

**Issue by chujian-fang** [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network#4]
I found when you draw the picture fig 1a fig1b fig2a fig2b,you load the data from a folder called data,which stored many data,I try to run your code ,I find that your program contains a lot of errors，I wonder how you come to the conclusion with wrong code. If it's my fault  I am sorry

**Comment by JSLee121230** [comment]
First, thank you for your comments.
I only tested matlab2019b with CVX. 
If you run a version other than matlab2019b, you may get many errors.
Would you like to try again in matlab2019b?

**Comment by chujain-fang** [comment]
Thank you for forgiving my rudeness，I run your code with matlab2018b，when I run the code,solveP3,There are some DCP errors,such as   Illegal operation: {concave} + {convex} ,and   as I konw ,norn(( Q(:,m) - u(:,k)))^2) is also against  DCP rules，because norm is convex，but  cvx will reject   expression  such as convex^2；Maybe I made a mistake, but I didn't realize, if so, please point it out, thank you,thanks for your time ！have a good day！

**Comment by chujian-fang** [comment]
Thank you for forgiving my rudeness，I run your code with matlab2018b，when I run the code,solveP3,There are some DCP errors,such as Illegal operation: {concave} + {convex} ,and as I konw ,norn(( Q(:,m) - u(:,k)))^2) is also against DCP rules，because norm is convex，but cvx will reject expression such as convex^2；Maybe I made a mistake, but I didn't realize, if so, please point it out, thank you,thanks for your time ！have a good day！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 上午10:19
收件人:&nbsp;"JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network"<Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network@noreply.github.com&gt;;
抄送:&nbsp;"不聚不散"<2485651587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network] There may be some problems here (#4)





 
First, thank you for your comments.
 I only tested matlab2019b with CVX.
 If you run a version other than matlab2019b, you may get many errors.
 Would you like to try again in matlab2019b?

**Comment by Braveman-sqtt** [comment]
Hello. I have read your code and found it very helpful to me. I want to ask you where do you execute the Save command to get the file Data. Thank you very much.

**Comment by JSLee121230** [comment]
The save command is on the last line of Figure1.m.

**Comment by Braveman-sqtt** [comment]
Thank you, I do recognize the save command but when I rename the save command and the load command. It doesn't work anymore even though I changed istrain to =1. Help me
