### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Braveman-sqtt** [JSLee121230/Energy-Ef-cient-Data-Collection-in-UAV-Enabled-Wireless-Sensor-Network#6]
How you can save the Data file. Please help me

**Comment by Braveman-sqtt** [comment]
I tried the way you said, but I can't save the Data. I changed the save file name and the Load file but it gives error when istrain = 1. Please tell me why.

**Comment by JSLee121230** [comment]
Can you tell me the error message?
I think that the solveP1 function didn't work in your environment.

**Comment by Braveman-sqtt** [comment]
I am very pleased for your kindness. I found the error and fixed it. Due to
different matlab versions, errors arise. Thank you very much.
In addition, I am also doing research on optimizing the power and flight
trajectory of the UAV. I am a new student with no experience, especially in
matlab simulation. Do you have any similar articles that I can refer to?
Sorry for my lack of courtesy. Thank you

Vào Th 2, 8 thg 11, 2021 vào lúc 10:10 Jongseok Lee <
***@***.***> đã viết:
